[build.environment]
  NODE_VERSION = "20"

[build]
  command = "pnpm build"
  environment = { NODE_VERSION = "20" }
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/manifest.webmanifest"
  [headers.values]
    Content-Type = "application/manifest+json"
