/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...path]': RouteRecordInfo<'/[...path]', '/:path(.*)', { path: ParamValue<true> }, { path: ParamValue<false> }>,
    '/about/': RouteRecordInfo<'/about/', '/about', Record<never, never>, Record<never, never>>,
    '/about/site': RouteRecordInfo<'/about/site', '/about/site', Record<never, never>, Record<never, never>>,
    '/archives/': RouteRecordInfo<'/archives/', '/archives', Record<never, never>, Record<never, never>>,
    '/categories/': RouteRecordInfo<'/categories/', '/categories', Record<never, never>, Record<never, never>>,
    '/links/': RouteRecordInfo<'/links/', '/links', Record<never, never>, Record<never, never>>,
    '/page/[page]': RouteRecordInfo<'/page/[page]', '/page/:page', { page: ParamValue<true> }, { page: ParamValue<false> }>,
    '/posts/algorithm/array': RouteRecordInfo<'/posts/algorithm/array', '/posts/algorithm/array', Record<never, never>, Record<never, never>>,
    '/posts/algorithm/stack': RouteRecordInfo<'/posts/algorithm/stack', '/posts/algorithm/stack', Record<never, never>, Record<never, never>>,
    '/posts/cocos/01.入门/1.入门': RouteRecordInfo<'/posts/cocos/01.入门/1.入门', '/posts/cocos/01/入门/1/入门', Record<never, never>, Record<never, never>>,
    '/posts/cocos/02.项目结构/项目结构': RouteRecordInfo<'/posts/cocos/02.项目结构/项目结构', '/posts/cocos/02/项目结构/项目结构', Record<never, never>, Record<never, never>>,
    '/posts/cocos/03.http服务/': RouteRecordInfo<'/posts/cocos/03.http服务/', '/posts/cocos/03/http服务', Record<never, never>, Record<never, never>>,
    '/posts/cocos/04.cors/': RouteRecordInfo<'/posts/cocos/04.cors/', '/posts/cocos/04/cors', Record<never, never>, Record<never, never>>,
    '/posts/cocos/05.非对称加密/': RouteRecordInfo<'/posts/cocos/05.非对称加密/', '/posts/cocos/05/非对称加密', Record<never, never>, Record<never, never>>,
    '/posts/cocos/06.mysql/': RouteRecordInfo<'/posts/cocos/06.mysql/', '/posts/cocos/06/mysql', Record<never, never>, Record<never, never>>,
    '/posts/cocos/07.哈希散列混淆/': RouteRecordInfo<'/posts/cocos/07.哈希散列混淆/', '/posts/cocos/07/哈希散列混淆', Record<never, never>, Record<never, never>>,
    '/posts/cocos/08.uuid生成token/': RouteRecordInfo<'/posts/cocos/08.uuid生成token/', '/posts/cocos/08/uuid生成token', Record<never, never>, Record<never, never>>,
    '/posts/cocos/09.gateway/': RouteRecordInfo<'/posts/cocos/09.gateway/', '/posts/cocos/09/gateway', Record<never, never>, Record<never, never>>,
    '/posts/cocos/10.grpc/': RouteRecordInfo<'/posts/cocos/10.grpc/', '/posts/cocos/10/grpc', Record<never, never>, Record<never, never>>,
    '/posts/cocos/11.protobuf/': RouteRecordInfo<'/posts/cocos/11.protobuf/', '/posts/cocos/11/protobuf', Record<never, never>, Record<never, never>>,
    '/posts/cocos/12.柏林噪声生成地图/': RouteRecordInfo<'/posts/cocos/12.柏林噪声生成地图/', '/posts/cocos/12/柏林噪声生成地图', Record<never, never>, Record<never, never>>,
    '/posts/css/回流和重绘': RouteRecordInfo<'/posts/css/回流和重绘', '/posts/css/回流和重绘', Record<never, never>, Record<never, never>>,
    '/posts/game/cocos开发mmoact游戏技术预研': RouteRecordInfo<'/posts/game/cocos开发mmoact游戏技术预研', '/posts/game/cocos开发mmoact游戏技术预研', Record<never, never>, Record<never, never>>,
    '/posts/music/01初识sonicpi': RouteRecordInfo<'/posts/music/01初识sonicpi', '/posts/music/01初识sonicpi', Record<never, never>, Record<never, never>>,
    '/posts/music/02乐理': RouteRecordInfo<'/posts/music/02乐理', '/posts/music/02乐理', Record<never, never>, Record<never, never>>,
    '/posts/music/03hithat': RouteRecordInfo<'/posts/music/03hithat', '/posts/music/03hithat', Record<never, never>, Record<never, never>>,
    '/posts/react/interview': RouteRecordInfo<'/posts/react/interview', '/posts/react/interview', Record<never, never>, Record<never, never>>,
    '/posts/react/react-hook': RouteRecordInfo<'/posts/react/react-hook', '/posts/react/react-hook', Record<never, never>, Record<never, never>>,
    '/posts/stableDffision/01.install': RouteRecordInfo<'/posts/stableDffision/01.install', '/posts/stableDffision/01/install', Record<never, never>, Record<never, never>>,
    '/posts/unity/1.入门': RouteRecordInfo<'/posts/unity/1.入门', '/posts/unity/1/入门', Record<never, never>, Record<never, never>>,
    '/posts/vite/loadEnv': RouteRecordInfo<'/posts/vite/loadEnv', '/posts/vite/loadEnv', Record<never, never>, Record<never, never>>,
    '/tags/': RouteRecordInfo<'/tags/', '/tags', Record<never, never>, Record<never, never>>,
  }
}
